EventManagement/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManagement.Models
{
    public class Event
    {
        public int EventId { get; set; }

        public string Name { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public string Description { get; set; }


        // Navigation properties
        public int EventTypeId { get; set; }
        public EventType EventType { get; set; }

        public List<EventDocument> EventDocuments { get; set; }
    }
}

EventManagement/Models/EventDocument.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManagement.Models
{
    public class EventDocument
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
    }
}

EventManagement/Models/EventType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManagement.Models
{
    public class EventType
    {
        public int EventTypeId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
}

EventManagement/Models/ViewModels/EventDocumentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManagement.Models.ViewModels
{
    public class EventDocumentsViewModel
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
    }
}

EventManagement/Models/ViewModels/EventsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventManagement.Models.ViewModels
{
    public class EventsListViewModel
    {
        public IEnumerable<Event> Events { get; set; }

        public string CurrentEventType { get; set; }
    }
}

EventManagement/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EventManagement.Data;
using Microsoft.EntityFrameworkCore;

namespace EventManagement.Components
{
    public class NavigationMenuViewComponent: ViewComponent
    {
        private ApplicationDBContext _context;
        public NavigationMenuViewComponent(ApplicationDBContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["eventType"];
            return View(
                _context.Events.Include(e=>e.EventType)
                .Select(x=>x.EventType.Name)
                .Distinct()
                .OrderBy(x=>x)
                );
        }
    }
}

EventManagement/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EventManagement.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventManagement.Models;
using System.IO;
using EventManagement.Models.ViewModels;

namespace EventManagement.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDBContext _context;
        public AdminController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View(_context.Events.Include(e=>e.EventDocuments));
        //{
        //    return View();
        //}

        public IActionResult Create()
        {
            PopulateEventTypeDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Event @event)
        {
            var files = HttpContext.Request.Form.Files;
            //long fl = HttpContext.Request.Form.Files.Sum(f => f.Length);

            var filePath = @"d:\123\";//Path.GetTempFileName();

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(@"d:\"+formFile.FileName, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            PopulateEventTypeDropDownList();
            return View(@event);
        }




        public async Task<IActionResult> Edit(int? eventId)
        {
            if (eventId == null)
            {
                return NotFound();
            }

            var Event = await _context.Events.FindAsync(eventId);

            var @event = await _context.Events
                .Include(e => e.EventDocuments)
                .AsNoTracking()
                .SingleOrDefaultAsync(e => e.EventId == eventId);

            //if (Event == null)
            //{
            //    return NotFound();
            //}

            //PopulateEventTypeDropDownList(Event.EventTypeId);
            //return View(Event);

            if (@event == null)
            {
                return NotFound();
            }

            PopulateEventTypeDropDownList(@event.EventTypeId);
            PopulateEventDocuments(@event);
            return View(@event);
        }

        [HttpPost,ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(Event @event)
        {
            if (ModelState.IsValid)
            {
                //_context.Add(@event);
                _context.Update(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }



        private void PopulateEventTypeDropDownList(object selectedEvent = null)
        {
            var eventTypesQuery = from d in _context.EventTypes
                                   orderby d.Name
                                   select d;
            ViewBag.EventTypeId = new SelectList(eventTypesQuery.AsNoTracking(), "EventTypeId", "Name", selectedEvent);

       
        }

        private void PopulateEventDocuments(Event @event)
        {
            var allDocuments = _context.EventDocuments;
            var eventDocument = new HashSet<string>(@event.EventDocuments.Select(e => e.FileName));
            //var viewModel = new List<EventDocumentsViewModel> ();
            //foreach (var doc in eventDocument)
            //{
            //    viewModel.Add(new EventDocumentsViewModel
            //    {
                    
            //    });
            //}

            ViewData["Documents"] = eventDocument.ToList();// viewModel;
        }
    }
}

EventManagement/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EventManagement.Data;
using EventManagement.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace EventManagement.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDBContext _context;
        public EventController(ApplicationDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult List(string eventType)
        {
            var events = new EventsListViewModel();
            events.Events = _context.Events
                .Include(t => t.EventType)
                .AsNoTracking();
            events.CurrentEventType = eventType;

            if (eventType!=null)
            {
                events.Events = events.Events.Where(e=>e.EventType.Name==eventType);
            }

            return View(events);
        }
    }
}

EventManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EventManagement.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EventManagement/Views/Admin/Create.cshtml
@model EventManagement.Models.Event

@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
}

<h2>Create</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            @*<div class="form-group">
            <label asp-for="EventId"></label>
            <input asp-for="EventId" class="form-control" />
        </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="EventTypeId" class="control-label"></label>
                <select asp-for="EventTypeId" class="form-control" asp-items="ViewBag.EventTypeId"></select>
                @*<span asp-validation-for="DepartmentID" class="text-danger"></span>*@
            </div>
            <input type="file" name="files" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
        <div>
            <a asp-action="List" asp-controller="Event">Back to List</a>
        </div>

    </div>
</div>

EventManagement/Views/Admin/Edit.cshtml
@model Event

@{
    ViewBag.Title = "Edit Event";
    Layout = "_AdminLayout";
}

<form asp-action="Edit" enctype="multipart/form-data" method="post">
    <input type="hidden" asp-for="EventId" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="EventTypeId" class="control-label"></label>
        <select asp-for="EventTypeId" class="form-control" asp-items="ViewBag.EventTypeId"></select>
        @*<span asp-validation-for="DepartmentID" class="text-danger"></span>*@
    </div>

    <input type="file" name="files"/>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

EventManagement/Views/Admin/Index.cshtml
@model IEnumerable<Event>
@{
    ViewData["Title"] = "Events";
    Layout = "_AdminLayout";
}

<table class="table table-striped table-bordered table-sm">
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.EventId</td>
            <td>@item.Name</td>
            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-eventId="@item.EventId">Edit</a>
                    <input type="hidden" name="EventId" value="@item.EventId" />
                    <button type ="submit" class=" btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Event</a>
</div>

EventManagement/Views/Event/List.cshtml
@model EventsListViewModel
@{
    ViewData["Title"] = "List";
}

@foreach (var e in Model.Events)
{
    @Html.Partial("EventSummary",e);
}

EventManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = null;
}

<h2>Index</h2>

<p>Hello from index view</p>

EventManagement/Views/Shared/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>

<a class="btn btn-block btn-outline-secondary"
   asp-action="List"
   asp-controller="Event"
   asp-route-eventType="">
    Home
</a>
@foreach (string eventType in Model)
{
    <a class="btn btn-block @(eventType == ViewBag.SelectedCategory ? "btn-primary": "btn-outline-secondary")"
       asp-action="List"
       asp-controller="Event"
       asp-route-eventType="@eventType">
        @eventType
    </a>
}

EventManagement/Views/Shared/EventSummary.cshtml
@model Event
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            

            @*<span class="badge badge-pill badge-primary" style="float:right">
                    <small>@p.Price.ToString("c")</small>
                </span>*@
        </h4>
        <div>
            @Model.EventType.Name
        </div>
    </div>
    <div class="card-text p-1">@Model.Description</div>
</div>

EventManagement/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>
<body class="m-1 p-1">
    <div class="bg-info p-2">@ViewBag.Title</div>
    @RenderBody() 
</body>
</html>

EventManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <title>EventManagement</title>
</head>
<body>
    <div class="navbar navbar-dark bg-primary" role="navigation">
        <a class="navbar-brand" href="#">Event Management</a>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>